"""freedom

Revision ID: 30481732a96c
Revises: f18c6a29b701
Create Date: 2018-01-03 16:04:25.024938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30481732a96c'
down_revision = 'f18c6a29b701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_interval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_day', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_day', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_free_interval_timestamp'), 'free_interval', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_free_interval_timestamp'), table_name='free_interval')
    op.drop_table('free_interval')
    # ### end Alembic commands ###
